import {heroui} from "@heroui/theme"

/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./index.html",
    './src/layouts/**/*.{js,ts,jsx,tsx,mdx}',
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    "./node_modules/@heroui/theme/dist/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {},
  },
  darkMode: "class",
  plugins: [heroui({
    themes: {
      light: {
        colors: {
          background: "#FFFFFF",
          foreground: "#11181C",
          divider: "rgba(17, 17, 17, 0.15)",
          focus: "#006FEE",
          content1: "#FFFFFF",
          content2: "#f4f4f5",
          content3: "#e4e4e7",
          content4: "#d4d4d8",
          default: {
            50: "#fafafa",
            100: "#f4f4f5",
            200: "#e4e4e7",
            300: "#d4d4d8",
            400: "#a1a1aa",
            500: "#71717a",
            600: "#52525b",
            700: "#3f3f46",
            800: "#27272a",
            900: "#18181b",
            foreground: "",
            background: "",
            divider: "",
            focus: "",
            DEFAULT: "#d4d4d8",
          },
          primary: {
            50: "#02BAF2",
            100: "#04B6EC",
            200: "#06B2E6",
            300: "#08ADE0",
            400: "#0AA9DA",
            500: "#0DA6D4",
            600: "#19A3CD",
            700: "#29A1C6",
            800: "#3EA4C3",
            900: "#53A0B7",
            foreground: "",
            background: "",
            divider: "",
            focus: "",
            DEFAULT: "#0DA6D4",
          },
          secondary: {
            50: "",
            100: "",
            200: "",
            300: "",
            400: "",
            500: "",
            600: "",
            700: "",
            800: "",
            900: "",
            foreground: "",
            background: "",
            divider: "",
            focus: "",
            DEFAULT: "#7828c8",
          },
          success: {
            50: "",
            100: "",
            200: "",
            300: "",
            400: "",
            500: "",
            600: "",
            700: "",
            800: "",
            900: "",
            foreground: "",
            background: "",
            divider: "",
            focus: "",
            DEFAULT: "#17c964",
          },
          warning: {
            50: "",
            100: "",
            200: "",
            300: "",
            400: "",
            500: "",
            600: "",
            700: "",
            800: "",
            900: "",
            foreground: "",
            background: "",
            divider: "",
            focus: "",
            DEFAULT: "#f5a524",
          },
          danger: {
            50: "",
            100: "",
            200: "",
            300: "",
            400: "",
            500: "",
            600: "",
            700: "",
            800: "",
            900: "",
            foreground: "",
            background: "",
            divider: "",
            focus: "",
            DEFAULT: "#f31260",
          },
        },
      },
      dark: {
        colors: {
          background: "",
          foreground: "",
          divider: "",
          focus: "",
          content1: "",
          content2: "",
          content3: "",
          content4: "",
          default: {
            50: "",
            100: "",
            200: "",
            300: "",
            400: "",
            500: "",
            600: "",
            700: "",
            800: "",
            900: "",
            foreground: "",
            background: "",
            divider: "",
            focus: "",
            DEFAULT: "",
          },
          primary: {
            50: "",
            100: "",
            200: "",
            300: "",
            400: "",
            500: "",
            600: "",
            700: "",
            800: "",
            900: "",
            foreground: "",
            background: "",
            divider: "",
            focus: "",
            DEFAULT: "",
          },
          secondary: {
            50: "",
            100: "",
            200: "",
            300: "",
            400: "",
            500: "",
            600: "",
            700: "",
            800: "",
            900: "",
            foreground: "",
            background: "",
            divider: "",
            focus: "",
            DEFAULT: "",
          },
          success: {
            50: "",
            100: "",
            200: "",
            300: "",
            400: "",
            500: "",
            600: "",
            700: "",
            800: "",
            900: "",
            foreground: "",
            background: "",
            divider: "",
            focus: "",
            DEFAULT: "",
          },
          warning: {
            50: "",
            100: "",
            200: "",
            300: "",
            400: "",
            500: "",
            600: "",
            700: "",
            800: "",
            900: "",
            foreground: "",
            background: "",
            divider: "",
            focus: "",
            DEFAULT: "",
          },
          danger: {
            50: "",
            100: "",
            200: "",
            300: "",
            400: "",
            500: "",
            600: "",
            700: "",
            800: "",
            900: "",
            foreground: "",
            background: "",
            divider: "",
            focus: "",
            DEFAULT: "",
          },
        },
      }
    }
  })],
}
